server:
  port: 5200

spring:
  application:
    name: thread-practice

  # 引入配置文件
  profiles:
    active: log,cleanLog,quartz

  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.96.178.201:3306/practice?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package:


# Spring线程池异步线程相关配置
async:
  executor:
    thread:
      # 核心线程数
      core_pool_size: 5
      # 最大线程数
      max_pool_size: 5
      # 队列大小
      queue_capacity: 99999
      name:
        prefix: async-service-
